# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbea46b1663ef4465651a507ef6f16cf7bea2febc53dbda9443851f3d8f1040caff1859fea9e0ba459db1adcb95e3d0a58d530fdad411485d010cd6ef3473152

test:
  secret_key_base: 80476e9487d61bd33dc4bded6a4f38d03ba2edd991e103de51ef971ba2410c4100281cc42414f78ba0436844d3266040af323eb38ea8d3a26f401d484be057c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
