# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f632d61e01a75c5f276e38cd8f6832fe7a58b39d730744dad283ac97b586d24bd4183f1bc3957f2e28399ec02c3d1d4130f4e7825b57d0574b291d95933aa789

test:
  secret_key_base: 69a1e1d9406e9c261ead7c00a83ce64c011015c918c3419bd0a3cda298119d5e5ff184327141d3230bdd43319f0cb657a67dad3ddc38cbf38844d5f361fbae23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
