# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82cf62cf65a8b55d4f41b8266849fd030f8f9b669f53a0132ca5959b838ed68b0c79600c71c786dd7d44866beccdcaffbb8bf71d99603e190cd31f22a86cbe7b

test:
  secret_key_base: 9ab68ae305e7af495b06c9a456301536e5e553af592f632cacf9cf8ba0b3cac114f383ef0519b68febee412199a67671ad6f603f470a6a8830fe7851e7971446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
